name: Terraform
on: pull_request
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: true